services:
  ordering_system_app:
    container_name: ordering_system_app
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: True
    tty: True
    restart: on-failure
    ports:
      - "8009:8009"
    volumes:
      - .:/app
    env_file:
      - .env
    