"""Adiciona atributo active para Order e OrderItems.

Revision ID: 36d47949781f
Revises: fd6f2ddd5f9c
Create Date: 2025-07-16 16:36:03.495418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36d47949781f'
down_revision: Union[str, Sequence[str], None] = 'fd6f2ddd5f9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
