"""Adiciona itens do pedido para pedido.

Revision ID: e67661f91f5d
Revises: 2c463dc748ce
Create Date: 2025-07-16 14:49:22.741096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e67661f91f5d'
down_revision: Union[str, Sequence[str], None] = '2c463dc748ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
