"""Adiciona atributo active para Order e OrderItems.

Revision ID: fd6f2ddd5f9c
Revises: e67661f91f5d
Create Date: 2025-07-16 15:42:29.221423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd6f2ddd5f9c'
down_revision: Union[str, Sequence[str], None] = 'e67661f91f5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itens_pedido', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('pedidos', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'active')
    op.drop_column('itens_pedido', 'active')
    # ### end Alembic commands ###
