name: OrderingSystem CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Criar e ativar ambiente virtual Python.
        run: |
          python3 -m venv venv
          source venv/bin/activate
          echo "source venv/bin/activate" >> $GITHUB_ENV

      - name: Configurar variáveis de ambiente
        run: |
          echo "ALGORITHM=${{ secrets.ALGORITHM }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "ACCESS_TOKEN_EXPIRE_MINUTES=${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env

      - name: Instalar dependências
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Rodar migrações com Alembic
        run: |
          source venv/bin/activate
          alembic upgrade head

      - name: Rodar testes
        run: |
          source venv/bin/activate
          pytest
